### ISSUE TITLE
Should it be licensed as GPLv3?

### ISSUE THREAD

**Issue by Vitalii3D-xyz** [CloakedWayne/Monolith_Gantry_V2-VT#2]
Considering that design is based on Voron gantry layout and the same location of motion system I believe that it should follow GPLv3 license from Voron repo. Am I wrong?

**Comment by Vitalii3D-xyz** [comment]
I had this discussion once with Voron team, details are here https://github.com/Vitalii3D-xyz/MetalTap/issues/1

**Comment by CloakedWayne** [comment]
This has a completely different belt path. Only the extrusion and rail lengths are the same to ensure compatibility. A team member reviewed my files before I pushed it under this license just in case.

**Comment by Vitalii3D-xyz** [comment]
Thanks for the answer, hope to use it on my machine one day!
