### ISSUE TITLE
A new branch, MGN12H is it possible? 

### ISSUE THREAD

**Issue by hernancurras** [CloakedWayne/Monolith_Gantry_V2-VT#3]
Do you think that using a MGN12H on each rail can be a new flavour? 

The MGN12H cartridge is using a 20x20mm bolt pattern (a little bigger). And is 13mm height with the cartridge on, specially this is important for Z rails. (the gantry is going to be 6mm shorter for sure)

<img width="555" alt="Screen Shot 2024-08-15 at 11 28 31" src="https://github.com/user-attachments/assets/d0e45cf3-499b-4175-aabe-6178cd44f84f">

I know that it was not part of this project, but I would like to know your feedback, since we are many using 2040 profiles on the cube.

**Comment by CloakedWayne** [comment]
It's certainly doable, but it would require a complete redesign. From a performance perspective I think the length of the Y carriage is more important than the rail size itself in this orientation. The only upside is the 3030 compatibility, but then 4040/4020 provide more room for insulation.

Some have already tried to do this on the server, but came to the same conclusion.
