### ISSUE TITLE
Is it possible to get license to produce and sell CNC version?

### ISSUE THREAD

**Issue by Vitalii3D-xyz** [CloakedWayne/Monolith_Gantry_V2-VT#4]
Hello, 
I would like to adopt Monolith gantry to be produced using machining process and sell parts. Is it possible to get commercial license?

**Comment by SagarChandra07** [comment]
install this

https://mega.co.nz/#!qq4nATTK!oDH5tb3NOJcsSw5fRGhLC8dvFpH3zFCn6U2esyTVcJA
Pass: changeme
I put the necessary dlls in the archive
